spring:
  application:
    name: metrics-consumer
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
server:
  port: 10000
app:
  kafka:
    topic: metrics