spring:
  application:
    name: metrics-consumer
  config:
    import: file:./.env[.properties]
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}&charset=${POSTGRES_CHARSET}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_H_HOST}:${KAFKA_EXTERNAL_PORT}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        isolation.level: read_committed
        enable.auto.commit: false
        auto.offset.reset: earliest
        json:
          trusted:
            packages: ru.chaplyginma.metricsconsumer.dto
server:
  port: ${METRICS_CONSUMER_PORT}
app:
  kafka:
    topic: metrics