spring:
  application:
    name: metrics-consumer
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:10001/metrics?serverVersion=16&charset=utf8
    username: metrics
    password: metrics
  kafka:
    bootstrap-servers: localhost:10002
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        isolation.level: read_committed
        enable.auto.commit: false
        auto.offset.reset: earliest
        json:
          trusted:
            packages: ru.chaplyginma.metricsconsumer.dto
server:
  port: 10000
app:
  kafka:
    topic: metrics