CREATE TABLE metric
(
    id               BIGINT           NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name      VARCHAR(255)     NOT NULL,
    metric_value     DOUBLE PRECISION NOT NULL,
    metric_timestamp TIMESTAMP        NOT NULL
);