server:
  port: ${METRICS_PRODUCER_PORT}
spring:
  application:
    name: metrics-producer
  config:
    import: file:./.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_H_HOST}:${KAFKA_EXTERNAL_PORT}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  kafka:
    topic: metrics