services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "echo stat | nc -w 2 localhost 2181" ]
      interval: 20s
      timeout: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "29092:29092"
    depends_on:
      zookeeper:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - kafka_gorch:/var/lib/kafka/data

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - 10001:5432
    volumes:
      - ./metrics-consumer/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  monitored-app:
    build:
      context: ./
      dockerfile: monitored-app/.docker/Dockerfile
    container_name: monitored-app
    depends_on:
      - metrics-producer

  metrics-producer:
    build:
      context: ./
      dockerfile: metrics-producer/.docker/Dockerfile
    container_name: metrics-producer
    depends_on:
      - kafka

  metrics-consumer:
    build:
      context: ./
      dockerfile: metrics-consumer/.docker/Dockerfile
    container_name: metrics-consumer
    depends_on:
      - kafka
      - postgres
    ports:
      - ${METRICS_CONSUMER_PORT}:${METRICS_CONSUMER_PORT}

volumes:
  kafka_gorch:
