services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "echo stat | nc -w 2 localhost 2181" ]
      interval: 20s
      timeout: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "29092:29092"
    depends_on:
      zookeeper:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - kafka_gorch:/var/lib/kafka/data

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - 10001:5432
    volumes:
      - ./metrics-consumer/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  kafka_gorch:
