openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:10020
    description: Generated server url
tags:
  - name: Metrics
    description: Endpoint for managing metrics
paths:
  /metrics:
    post:
      tags:
        - Metrics
      summary: Add Metrics
      description: Add new metrics data to kafka
      operationId: postMetrics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMetricDto'
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
        "201":
          description: Metrics added successfully
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: Invalid input data
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    AddMetricDto:
      required:
        - metricName
        - metricTimestamp
      type: object
      properties:
        metricName:
          maxLength: 255
          minLength: 0
          type: string
          description: Name of the metric
          example: CPU Usage
        metricValue:
          type: number
          description: Value of the metric
          format: double
          example: 0.75
        metricTimestamp:
          type: string
          description: Timestamp of the metric data
          format: date-time
      description: Metrics data to add
