openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:10020
  description: Generated server url
tags:
- name: Metrics
  description: Endpoint for managing metrics
paths:
  /metrics:
    post:
      tags:
      - Metrics
      summary: Add Metrics
      description: Add new metrics data to kafka
      operationId: postMetrics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMetricsDto'
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
        "201":
          description: Metrics added successfully
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: Invalid input data
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    AddMetricsDto:
      required:
      - metricName
      - timestamp
      type: object
      properties:
        metricName:
          type: string
          description: Name of the metric
          example: CPU Usage
        value:
          type: number
          description: Value of the metric
          format: double
          example: 0.75
        timestamp:
          type: string
          description: Timestamp of the metric data
          format: date-time
      description: Metrics data to add
