app:
    monitored:
        metrics: disk.free,process.cpu.usage,jvm.memory.used
management:
    endpoints:
        web:
            exposure:
                include: metrics
    server:
        port: ${MONITORED_APP_ACTUATOR_PORT}
metricsproducer:
    api-url: http://${METRICS_PRODUCER_HOST}:${METRICS_PRODUCER_PORT}/metrics
server:
    port: ${MONITORED_APP_PORT}
spring:
    application:
        name: monitored-app
    config:
        import: file:./.env[.properties]
